---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add IPv4 ICMP ingress rules to default security group
      openstack.cloud.security_group_rule:
        security_group: default
        direction: ingress
        protocol: icmp
        ether_type: IPv4
        remote_ip_prefix: 0.0.0.0/0

    - name: Add IPv6 ICMP ingress rules to default security group
      openstack.cloud.security_group_rule:
        security_group: default
        direction: ingress
        protocol: icmp
        ether_type: IPv6
        remote_ip_prefix: ::/0

    - name: Add IPv4 TCP ingress rules to default security group
      openstack.cloud.security_group_rule:
        security_group: default
        direction: ingress
        protocol: tcp
        ether_type: IPv4
        port_range_min: '{{ item }}'
        port_range_max: '{{ item }}'
        remote_ip_prefix: 0.0.0.0/0
      with_items:
        - 22
        - 80

    - name: Add IPv6 TCP ingress rules to default security group
      openstack.cloud.security_group_rule:
        security_group: default
        direction: ingress
        protocol: tcp
        ether_type: IPv6
        port_range_min: '{{ item }}'
        port_range_max: '{{ item }}'
        remote_ip_prefix: ::/0
      with_items:
        - 22
        - 80
