---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create server
      openstack.cloud.server:
        state: present
        name: precarious_puffin
        image: 'Ubuntu 22.04.1 Jammy Jellyfish 230124'
        flavor: b.2c4gb
        volume_size: 16
        boot_from_volume: true
        terminate_volume: true
        key_name: ansible_key
        network: ansible_net
        auto_ip: true
        security_groups: default
        wait: true

    - name: Progress Check -- Server created
      file:
        path: ~/.prchk_server_created
        state: directory
